import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import { Providers } from './providers';
import { Navbar } from './features/header/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Draw App',
  description: 'Generated by me'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressContentEditableWarning>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
          <Toaster position="top-center" richColors={true} />
        </Providers>
      </body>
    </html>
  );
}
